name: ci

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "18"
      - run: yarn
      - run: yarn start-sandbox
      - run: yarn test
