name: Contract Testing Pipeline

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "17"
      - name: Install Git
        run: sudo apt install git -y
      - name: Install node modules
        run: yarn
      - name: Install compiler and linker
      - run: yarn everdev sol set --compiler 0.57.3 --linker 0.14.38
      - name: Give the right to launch the sandbox
        run: chmod 777 ./ci/sandbox.sh
      - name: Run sandbox in background
        run: ./ci/sandbox.sh
      - name: Compile and test contracts
        run: yarn test
